name: Verify Build

on: 
  push:
    branches:
      - master
      - 'release/**'
      - '**-feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Test
      run: mvn clean verify
    
    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar -Dsonar.projectKey=test-estimate-hub -Dsonar.organization=nishadchayanakhawa -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
